<a href="https://colab.research.google.com/github/JeannePul/Building_Makemore_in_Youtube/blob/main/Building_Makemore_1_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 1

 Train a trigram language model, i.e. take two characters as an input to predict the 3rd one. Feel free to use either counting or a neural net. Evaluate the loss; Did it improve over a bigram model?

In [ ]:
import torch

In [ ]:
words = open('names.txt', "r" ).read().splitlines()

In [ ]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}

In [ ]:
xs, ys = [], []

for w in words[:1]:
  chs =  ['.'] + ['.'] + list(w) + ['.']  # For our model, it is also very important to know what "Start" & "End-characters" are.
  for ch1, ch2, ch3 in zip(chs, chs[1:], chs[2:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    ix3 = stoi[ch3]
    # print( ch1, ch2, ch3)
    xs.append((ix1,ix2))
    ys.append(ix3)

xs = torch.tensor(xs)
ys = torch.tensor(ys)
print(xs[0].shape, xs.shape, ys)

torch.Size([2]) torch.Size([5, 2]) tensor([ 5, 13, 13,  1,  0])


In [ ]:
import torch.nn.functional as F
xenc = F.one_hot(xs, num_classes = 27)
xenc = xenc.float()

"""
How do i deal with 2 inputs? I put them next to each other.
For this to work I first have to convert them to a list, so I can append them.

Note: I am sure there is a more efficient and easy way to do it...
"""

xenc_54 = []
for i in range(len(xs)):
  a = xenc[i][0].tolist()
  b = xenc[i][1].tolist()
  ab = a + b
  xenc_54.append(ab)

xenc_54 = torch.tensor(xenc_54) # -> We get a 54-long input vector, not 27!
print(xenc_54)

"""
xenc_54 is now the whole input of the first word.
"""

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0.,

'\nxenc_54 is now the whole input of the first word.\n'

In [ ]:
W = torch.rand((54,27)) # The dimension of our weights have to match the input!
xenc_54 @ W # first pass through our NN

tensor([[1.0126, 1.3068, 1.2511, 1.1278, 0.7323, 1.7860, 1.0280, 1.2079, 0.9577,
         1.0034, 1.1422, 0.7177, 0.3020, 1.1308, 1.0603, 0.7632, 1.9147, 0.8420,
         1.7797, 0.9094, 0.5670, 1.0212, 1.1307, 0.4419, 0.5611, 0.5193, 1.1965],
        [1.1428, 1.5073, 1.6399, 1.5626, 0.8416, 1.8569, 0.3914, 0.8693, 1.8135,
         1.2209, 0.6740, 0.2783, 0.6055, 1.4479, 0.7545, 0.7687, 1.2532, 0.9835,
         1.8178, 1.1408, 1.2117, 1.3541, 0.9437, 0.5598, 0.4213, 1.1189, 0.5651],
        [1.2855, 0.9100, 0.9666, 1.2978, 0.1994, 0.2689, 1.5140, 1.5817, 1.0722,
         1.3607, 1.5112, 0.7861, 0.7734, 1.2677, 0.6243, 1.2229, 0.1635, 1.3436,
         0.7974, 1.3431, 0.9738, 0.9421, 1.2220, 0.9810, 0.7244, 1.2382, 0.4477],
        [0.9086, 0.7706, 0.8170, 0.7797, 0.4709, 0.6074, 0.8985, 1.6370, 0.7162,
         1.2440, 1.0091, 1.0744, 1.0407, 1.4227, 0.6049, 0.7674, 0.5781, 1.1583,
         0.9407, 0.5896, 1.4844, 0.9898, 1.3896, 0.8830, 1.1487, 1.5050, 0.1635],
        [0.6158, 1.4113,

In [ ]:
# Output

logits = xenc_54 @ W # log-counts

counts = logits.exp()
probs = counts / counts.sum(1, keepdims=True) # = softmax

probs

tensor([[0.0341, 0.0458, 0.0433, 0.0383, 0.0258, 0.0740, 0.0347, 0.0415, 0.0323,
         0.0338, 0.0388, 0.0254, 0.0168, 0.0384, 0.0358, 0.0266, 0.0841, 0.0288,
         0.0735, 0.0308, 0.0219, 0.0344, 0.0384, 0.0193, 0.0217, 0.0208, 0.0410],
        [0.0362, 0.0521, 0.0595, 0.0550, 0.0268, 0.0739, 0.0171, 0.0275, 0.0707,
         0.0391, 0.0226, 0.0152, 0.0211, 0.0491, 0.0245, 0.0249, 0.0404, 0.0308,
         0.0710, 0.0361, 0.0387, 0.0447, 0.0296, 0.0202, 0.0176, 0.0353, 0.0203],
        [0.0462, 0.0317, 0.0336, 0.0468, 0.0156, 0.0167, 0.0581, 0.0621, 0.0373,
         0.0498, 0.0579, 0.0280, 0.0277, 0.0454, 0.0239, 0.0434, 0.0150, 0.0490,
         0.0284, 0.0489, 0.0338, 0.0328, 0.0434, 0.0341, 0.0264, 0.0441, 0.0200],
        [0.0335, 0.0292, 0.0306, 0.0295, 0.0216, 0.0248, 0.0332, 0.0695, 0.0277,
         0.0469, 0.0371, 0.0396, 0.0383, 0.0561, 0.0248, 0.0291, 0.0241, 0.0431,
         0.0346, 0.0244, 0.0596, 0.0364, 0.0542, 0.0327, 0.0426, 0.0609, 0.0159],
        [0.0252, 0.0557,

In [ ]:
print(probs[torch.arange(len(xs)), ys])

tensor([0.0740, 0.0491, 0.0454, 0.0292, 0.0252])


In [ ]:
probs.shape

torch.Size([5, 27])

In [ ]:
nlls = torch.zeros(len(xs)) # emma provides us with 5 examples
for i in range(len(xs)):
  # i-th bigram:
  x = xs[i].tolist() # input character index
  y = ys[i].item() # label character index
  print('--------')
  print(x, y)
  print(f'bigram example {i+1}: {itos[x[0]]}{itos[x[1]]}  ->  {itos[y]} (Indexes ({x[0]},{x[1]}), {y})')
  print('input to the neural net:', x, '\n')
  print('output probabilities from the neural net:', probs[i], '\n')
  p = probs[i, y]
  print('probability assigned by the net to the the correct character:', p.item(), '\n')

  logp = torch.log(p)
  print('log likelihood:', logp.item())
  nll = -logp
  print('negative log likelihood:', nll.item(), '\n')
  nlls[i] = nll

print('=========', '\n')
print('average negative log likelihood, i.e. loss =', nlls.mean().item())


--------
[0, 0] 5
bigram example 1: ..  ->  e (Indexes (0,0), 5)
input to the neural net: [0, 0] 

output probabilities from the neural net: tensor([0.0341, 0.0458, 0.0433, 0.0383, 0.0258, 0.0740, 0.0347, 0.0415, 0.0323,
        0.0338, 0.0388, 0.0254, 0.0168, 0.0384, 0.0358, 0.0266, 0.0841, 0.0288,
        0.0735, 0.0308, 0.0219, 0.0344, 0.0384, 0.0193, 0.0217, 0.0208, 0.0410]) 

probability assigned by the net to the the correct character: 0.07395273447036743 

log likelihood: -2.6043291091918945
negative log likelihood: 2.6043291091918945 

--------
[0, 5] 13
bigram example 2: .e  ->  m (Indexes (0,5), 13)
input to the neural net: [0, 5] 

output probabilities from the neural net: tensor([0.0362, 0.0521, 0.0595, 0.0550, 0.0268, 0.0739, 0.0171, 0.0275, 0.0707,
        0.0391, 0.0226, 0.0152, 0.0211, 0.0491, 0.0245, 0.0249, 0.0404, 0.0308,
        0.0710, 0.0361, 0.0387, 0.0447, 0.0296, 0.0202, 0.0176, 0.0353, 0.0203]) 

probability assigned by the net to the the correct character: 0.

### Training

In [ ]:
xs, ys = [], []

for w in words[:]:
  chs =  ['.'] + ['.'] + list(w) + ['.']  # For our model, it is also very important to know what "Start" & "End-characters" are.
  for ch1, ch2, ch3 in zip(chs, chs[1:], chs[2:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    ix3 = stoi[ch3]
    # print( ch1, ch2, ch3)
    xs.append((ix1,ix2))
    ys.append(ix3)

xs = torch.tensor(xs)
ys = torch.tensor(ys)
num= xs.shape[0]
print(xs.shape, ys.shape)
print('number of examples: ', num)

# initialize the 'network'
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((54, 27), generator=g, requires_grad=True)

torch.Size([228146, 2]) torch.Size([228146])
number of examples:  228146


In [ ]:
xenc = F.one_hot(xs, num_classes = 27)
xenc = xenc.float()
z = xenc.shape[0]

xenc_54 = []
for i in range(z):
  a = xenc[i][0].tolist()
  b = xenc[i][1].tolist()
  ab = a + b
  xenc_54.append(ab)
xenc_54 = torch.tensor(xenc_54)

for k in range(100):

  #forward pass

  logits = xenc_54 @ W # log-counts
  counts = logits.exp() # equivalent to N
  probs = counts / counts.sum(1, keepdims=True) # = softmax

  loss = - probs[torch.arange(num), ys].log().mean()
  print('Iteration:', k+1, '   Loss:' , loss.item())


  # backward pass
  W.grad = None # set to zero the gradient
  loss.backward()

  # update
  W.data += -50 * W.grad


Iteration: 1    Loss: 4.232541084289551
Iteration: 2    Loss: 3.504002332687378
Iteration: 3    Loss: 3.318845510482788
Iteration: 4    Loss: 2.957639455795288
Iteration: 5    Loss: 2.863344192504883
Iteration: 6    Loss: 2.8381974697113037
Iteration: 7    Loss: 2.7508206367492676
Iteration: 8    Loss: 2.7523350715637207
Iteration: 9    Loss: 2.6745989322662354
Iteration: 10    Loss: 2.679236888885498
Iteration: 11    Loss: 2.626859188079834
Iteration: 12    Loss: 2.6468143463134766
Iteration: 13    Loss: 2.5863289833068848
Iteration: 14    Loss: 2.603274345397949
Iteration: 15    Loss: 2.561227321624756
Iteration: 16    Loss: 2.589733362197876
Iteration: 17    Loss: 2.536099672317505
Iteration: 18    Loss: 2.558943510055542
Iteration: 19    Loss: 2.5216567516326904
Iteration: 20    Loss: 2.5544543266296387
Iteration: 21    Loss: 2.503983736038208
Iteration: 22    Loss: 2.529757261276245
Iteration: 23    Loss: 2.4951326847076416
Iteration: 24    Loss: 2.530426502227783
Iteration: 25   

### Sample the NN

In [ ]:
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [ ]:
g = torch.Generator().manual_seed(2147483647)

for i in range(100):

  out = []
  ix = [0,0]
  while True:
    xenc = F.one_hot(torch.tensor(ix), num_classes=27).float()
    z = xenc.shape[0]
    a = xenc[0].tolist()
    b = xenc[1].tolist()
    ab = a + b
    xenc_54 = torch.tensor(ab)


    logits = xenc_54 @ W # predict log-counts
    counts = logits.exp() # counts, equivalent to N
    p = counts/counts.sum(0, keepdims=True) # probabilities for next character

    ix_b = torch.multinomial(p, num_samples=1, replacement=True, generator=g)
    ix_int =int(ix_b)
    """
    Careful! I had problems here, since itos[ix] did not work.
    I cannot call upon a dict with a tensor object!
    """
    out.append(itos[ix_int])

    """
    Now I have to construct my next input.
    The NN with just 1 input was easy, I could just use the output. Here I have to build my next input.
    """

    ix_a = int(ix[1])
    ix_b = ix_int

    if ix_int == 0:
      break
    else: # We only have to build the next input, if we don't didn't get a end-signal.
      ix = [ix_a, ix_b]

  print(''.join(out))

juwide.
janasaz.
pariay.
ainn.
kai.
ritoleras.
the.
adannaauranileniassibdainrwi.
ta.
saisiely.
arte.
farmumarif.
dammer.
fyns.
jah.
jayl.
core.
yaenockay.
aabdin.
jamikim.
ynil.
anaasnassoimonselhadgon.
mattanil.
arie.
alethat.
jayreli.
iah.
dyn.
rajemur.
mah.
dawyle.
kay.
caarr.
janh.
adorta.
malynabel.
ha.
ialavarocbethemielya.
ar.
fa.
sely.
tavilatikyasaloe.
marnandewkfabjanelah.
ahen.
ch.
kaura.
odridrdzerlialiyphrgha.
tazrwen.
aa.
vawh.
elvan.
haviobdandel.
gmil.
brasabdoni.
pexania.
arenn.
jaylandais.
caremyn.
mariannjed.
adomarelli.
deriganden.
dan.
vadon.
basstentti.
abus.
dasa.
la.
tan.
codfina.
asdoshatalieondeslef.
dariv.
mashama.
va.
hannge.
jardiynivion.
urien.
jalivnal.
alle.
marafjlanlynialey.
maritriyl.
arsoiredertiparkenniyaneria.
ahul.
la.
acvatavryael.
sabrla.
sa.
puralialieri.
kazinarahhiha.
ia.
jasaileorvann.
audcelaz.
arieertiliahadayra.
fbrlya.
caeyton.
za.
sabran.
ardeve.
zasslen.
conak.
na.
